---
title: "Lecture 12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set-up HIV-Pr for docking study

Get the protein first (i.e. download)
```{r}
library(bio3d)
file.name <- get.pdb("1hsg")
```

Read this file in and trim out the protein and small molecule ligand from everything else

```{r}
hiv <- read.pdb(file.name)
hiv
```


```{r}
ligand <- trim.pdb(hiv, "ligand")
ligand
```

Extract protein

```{r}
protein <- trim.pdb(hiv, "protein")
protein
```


```{r}
write.pdb(ligand, "1hsg_ligand.pdb")
write.pdb(protein, "1hsg_protein.pdb")
```


```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi = TRUE)
write.pdb(res, "results.pdb")
```

```{r}
ori <- read.pdb("ligand.pdbqt")
rmsd(ori, res)
```


> **Q6.** RMSD based on non hydrogen atoms

```{r}
inds <- atom.select(ori, "noh")

rmsd(ori$xyz[, inds$xyz], res$xyz[, inds$xyz])
```

## Revisit search and retrieve Adenylate kinase

```{r}
aa <- get.seq("P69441")
aa
```

```{r}
b <- blast.pdb(aa)
hits <- plot(b)
```

```{r}
hits <- plot(b)
```

```{r}
hits$pdb.id
```

```{r}
b$hit.tbl
```

```{r}
# Fetch PDBs
files <- get.pdb(hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```

```{r}
install.packages("bio3d.tar.gz", repos = NULL)
```

```{r}
# Align & superimpose structures
pdbs <- pdbaln(files, fit=TRUE)
```

```{r}
#view(pbds)
```

```{r}
# Perform PCA & plot the results
pc.xray <- pca(pdbs)
plot(pc.xray)
```

```{r}
pc1 <- mktrj(pc.xray, pc = 1, file = "pc_1.pdb")
# Calculate RMSD
rd <- rmsd(pdbs)
# Structure-based clustering
hc.rd <- hclust(dist(rd))
grps.rd <- cutree(hc.rd, k=3)
```




